[colors.primary]
background = "#0a0a0c"
foreground = "#b2b5b3"

[colors.cursor]
text = "#0a0a0c"
cursor = "#b2b5b3"

[colors.vi_mode_cursor]
text = "#0a0a0c"
cursor = "#b2b5b3"

[colors.search.matches]
foreground = "#0a0a0c"
background = "#e7e7e7"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#363638"
background = "#b2b5b3"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0a0a0c"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#4abaaf"
white = "#b2b5b3"

[colors.bright]
black = "#363638"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#4abaaf"
white = "#e7e7e7"

[colors.dim]
black = "#e7e7e7"
red = "#f7768e"
green = "#bb9af7"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#9ece6a"
cyan = "#4abaaf"
white = "#363638"

